{
    'name':    'Lira — Suite Financiera',
    'version': '18.0.2.1.1',
    'summary': 'Suite completa de análisis financiero: KPIs, ratios, ventas, escandallo, márgenes por cliente, previsión de liquidez y salarios, existencias, VAN/TIR, gráficas',
    'author':  'Apunts Informàtica',
    'website': 'http://www.grupapunts.es',
    'category': 'Accounting',
    'depends': ['accountant', 'account_accountant', 'sale_management', 'stock', 'purchase', 'mrp'],
    'data': [
        'security/ir.model.access.csv',
        'views/lira_variable_account_views.xml',
        'data/lira_variable_accounts_data.xml',
        'views/lira_dashboard_views.xml',
        'views/lira_forecast_views.xml',
        'views/lira_graficas_views.xml',
        'views/lira_sales_analysis_views.xml',
        'views/lira_product_costing_views.xml',
        'views/lira_customer_margin_views.xml',
        'views/lira_salary_forecast_views.xml',
        'views/lira_stock_valuation_views.xml',
        'views/lira_van_tir_views.xml',
        'views/lira_aging_views.xml',
        'views/lira_purchase_analysis_views.xml',
        'views/lira_collections_views.xml',
        'views/lira_pending_delivery_views.xml',
        'views/lira_mrp_wip_views.xml',
        'views/lira_mrp_products_views.xml',
        'views/lira_hacienda_views.xml',
        'views/lira_purchase_pending_views.xml',
        'views/lira_sales_monthly_views.xml',
        'views/lira_wip_valuation_views.xml',
        'views/lira_pnl_period_views.xml',
        'views/lira_inventory_valuation_fv_views.xml',
        'views/lira_aging_suppliers_views.xml',
        'views/lira_modelo_347_views.xml',
        'views/lira_modelo_111_115_views.xml',
        'views/lira_mercaderia_views.xml',
        'views/lira_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'lira_dashboard_contabilidad/static/src/css/dashboard.css',
            'lira_dashboard_contabilidad/static/src/js/lira_print.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
